theme: minima
title: קבוצת המשתמשים הישראלית של QGIS
minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/qgis-il"
    - title: QGIS הקהילה הישראלית בfacebook
      icon: facebook
      url: "https://www.facebook.com/groups/qgisinisrael"
    - title: QGIS בעברית בwhatsapp
      icon: whatsapp
      url: "https://chat.whatsapp.com/LcMSbVONvAU0sddIpHCPo4"
    - title: QGIS בעברית בtelegram
      icon: telegram
      url: "https://t.me/+YGfmzKHNnlgyMjVk"
    - title: QGIS-IL בYouTube
      icon: youtube
      url: "https://www.youtube.com/@QGIS-IL"
